### ISSUE TITLE
Use react router 6

### ISSUE THREAD

**Issue by mnlbox** [oedotme/render#1]
Hi @oedotme really appreciate your work. It's so clean and useful.

Just one request. Since some apisare charged on React Router 6 compare to version that you used in your tutorial, I think it's so useful if you can update this repo and your tutorial to the latest vversion of React Router.

Again thanks for your work.

**Comment by oedotme** [comment]
Thanks a lot for your feedback and suggestion!

Yeah I have that in mind, and also plan to write about the upgrade along with updating this repo soon.
