### ISSUE TITLE
Nested layout

### ISSUE THREAD

**Issue by iamyuu** [oedotme/render#4]
Hi, thanks for your work! I think it'll nice for supporting nested layout

#### Expected

similar behaviour with [basic example react-location](https://codesandbox.io/s/github/tannerlinsley/react-location/tree/main/examples/basic?file=/src/index.tsx:679-1229)

```
- Posts (has a list of posts with outlet)
|-- PostIndex
|-- DetailPost :id
```

when navigating from index to detail post, only re-render the outlet

**Comment by oedotme** [comment]
Hey Yusuf, thanks for the suggestion!

I was working on that and just pushed the nested layouts support to the template. You can find the implementation at [src/config/routes.tsx](https://github.com/oedotme/render/blob/main/src/config/routes.tsx)

It's inspired by [Remix's nested routes](https://remix.run/docs/en/v1/guides/routing#what-are-nested-routes).

I'll be publishing a blog post about it soon and update the readme as well.

**Comment by oedotme** [comment]
Just published the post covering that, you can find it here: https://omarelhawary.me/blog/file-based-routing-with-react-location-nested-layouts
