### ISSUE TITLE
Integration of Generouted

### ISSUE THREAD

**Issue by dewdad** [oedotme/render#5]
I love the approach you've implemented with Generouted. I'm pretty new to React, as a Vue comer.

**Comment by dewdad** [comment]
I'm interested whether you plan on having the template integrate your excellent genrouted library.

**Comment by oedotme** [comment]
Thanks a lot for your feedback and suggestion!

I added `generouted` to Render locally to test it and was also  planning to update Render docs/readme but didn't have the time, I'll try to push those updates soon.

**Comment by oedotme** [comment]
Render now uses `generouted` for file-based routing. https://github.com/oedotme/render/commit/6cdf9dc5dff16e8cacb13cab85c99f12d21c8784
