### ISSUE TITLE
Why You still recommended NextJs?

### ISSUE THREAD

**Issue by hscstudio** [oedotme/render#6]
Why You still recommended NextJs after you can create something like it? Or why you not create for example: refine.dev?

But, Many applications no need SSR.. no need SEO.. Many application want stay work at offline network.. and SSR Next cannot do that.. Client side react can do.. and simple deployment

Nice to see your library.. good job..

**Comment by oedotme** [comment]
Next.js is a great tool/ecosystem for React that's why I'm recommending it :)

[In the recommendation section](https://github.com/oedotme/render#recommendations), I intended to mention some complementary and alternative tools for what's used in Render.
