### ISSUE TITLE
[Req] Add unit/e2e test with MSW

### ISSUE THREAD

**Issue by sprabowo** [oedotme/render#7]
Dear @oedotme,

really appreciate your works, whether it is possible to add vitest (MSW) and cypress to this template? it'd be helpful to replace CRA template with this. 

thanks

**Comment by oedotme** [comment]
Hey @sprabowo, thanks for the suggestion and apologize for the late reply.

I've been using [Playwright](https://playwright.dev) for both end-to-end and unit tests and it works very well. I've set it up with this repo, here's the reference commit 17c869a
