### ISSUE TITLE
"Missing script start or file server.js" error when executing pnpm start command

### ISSUE THREAD

**Issue by theperiscope** [oedotme/render#9]
OS: Windows

```
pnpm start
```

> _ERR_PNPM_NO_SCRIPT_OR_SERVER  Missing script start or file server.js_

I think, based on current _package.json_ script definitions, the _pnpm start_ command listed in README.md should be changed to `pnpm preview`.

**Comment by oedotme** [comment]
Thanks @theperiscope, it's now updated to `pnpm preview`.
